#include "Display.h"
#include "pch.h"
#include "../MiniEngine/Core/GameCore.h"
#include "../MiniEngine/Core/GraphicsCore.h"
#include "../MiniEngine/Core/SystemTime.h"
#include "../MiniEngine/Core/TextRenderer.h"
#include "GameInput.h"
#include "PostEffects.h"
#include "UploadBuffer.h"
#include "../MiniEngine/Core/CommandContext.h"
#include "../MiniEngine/Core/RootSignature.h"
#include "../MiniEngine/Core/PipelineState.h"
#include "../MiniEngine/Core/BufferManager.h"

#include "Volumarcher.h"


using namespace GameCore;
using namespace Graphics;

enum class Test
{
	BaseSampleCountSingle,
	CloudCoverage,
	Resolution,
	None
};

static Test g_currentTest;

static constexpr uint MAX_FRAMES_PER_TEST_PHASE = 300;

static uint base_samples = 128;
static uint direct_samples = 16;
static uint ambient_samples = 4;

static constexpr uint sampleCountTestSamples[10]
{
	4,
	8,
	16,
	32,
	64,
	128,
	256,
	512,
	1024,
};

static constexpr float coverageCloudDistance[9]
{
	0.5f,
	1.f,
	2.f,
	4.f,
	8.f,
	15.f,
	20.f,
	30.f,
	50.f,
};

static constexpr glm::ivec2 resolutions[8]
{
	{320, 180},
	glm::ivec2(320, 180) * 2,
	glm::ivec2(320, 180) * 3,
	glm::ivec2(320, 180) * 4, // 720p
	glm::ivec2(320, 180) * 5,
	glm::ivec2(320, 180) * 6, // 1080p
	glm::ivec2(320, 180) * 8,
	glm::ivec2(320, 180) * 12, // 4k
};



class PerformanceTestApplication : public GameCore::IGameApp
{
public:
	PerformanceTestApplication()
	{
	}

	void Startup(void) override;

	void Cleanup(void) override;

	void Update(float deltaT) override;

	void InitRasterizor();

	void RenderRasterizerPass();

	void StartTest();

	void RenderScene(void) override;

private:
	std::unique_ptr<Volumarcher::VolumetricContext> m_volumetricContext;
	glm::vec3 m_camPos{0.f};
	glm::quat m_camRot{glm::identity<glm::quat>()};
	float m_camYaw{0.f};
	float m_camPitch{0.f};
	const float m_cameraSpeed{2.f};
	const float m_cameraRotSpeed{0.7f};


	int framesInTest = 0;
	int testPhase;
	ScopedTimer* pixTestTimer;
	CpuTimer cpuTestTimer;

	//Cube/Rasterizor stuff
	StructuredBuffer vertexBuffer;
	StructuredBuffer indexBuffer;

	RootSignature g_RootSig;
	GraphicsPSO g_CubePSO;
};

#pragma region Cube

//Cube code generated by ChatGPT
struct Vertex
{
	float position[3];
	float normal[3];
};

static const Vertex cubeVertices[] =
{
	// Front face (-Z)
	{{-1, -1, -1}, {0, 0, -1}},
	{{1, -1, -1}, {0, 0, -1}},
	{{1, 1, -1}, {0, 0, -1}},
	{{-1, 1, -1}, {0, 0, -1}},

	// Back face (+Z)
	{{-1, -1, 1}, {0, 0, 1}},
	{{1, -1, 1}, {0, 0, 1}},
	{{1, 1, 1}, {0, 0, 1}},
	{{-1, 1, 1}, {0, 0, 1}},

	// Left face (-X)
	{{-1, -1, -1}, {-1, 0, 0}},
	{{-1, 1, -1}, {-1, 0, 0}},
	{{-1, 1, 1}, {-1, 0, 0}},
	{{-1, -1, 1}, {-1, 0, 0}},

	// Right face (+X)
	{{1, -1, -1}, {1, 0, 0}},
	{{1, 1, -1}, {1, 0, 0}},
	{{1, 1, 1}, {1, 0, 0}},
	{{1, -1, 1}, {1, 0, 0}},

	// Top face (+Y)
	{{-1, 1, -1}, {0, 1, 0}},
	{{1, 1, -1}, {0, 1, 0}},
	{{1, 1, 1}, {0, 1, 0}},
	{{-1, 1, 1}, {0, 1, 0}},

	// Bottom face (-Y)
	{{-1, -1, -1}, {0, -1, 0}},
	{{1, -1, -1}, {0, -1, 0}},
	{{1, -1, 1}, {0, -1, 0}},
	{{-1, -1, 1}, {0, -1, 0}},
};

static const uint16_t cubeIndices[] =
{
	// Front face
	0, 1, 2, 0, 2, 3,
	// Back face
	4, 5, 6, 4, 6, 7,
	// Left face
	8, 9, 10, 8, 10, 11,
	// Right face
	12, 13, 14, 12, 14, 15,
	// Top face
	16, 17, 18, 16, 18, 19,
	// Bottom face
	20, 21, 22, 20, 22, 23
};

struct MatrixBuffer
{
	glm::mat4 MVP;
};

#include "CompiledShaders/PixelShader.h"
#include "CompiledShaders/VertexShader.h"

void PerformanceTestApplication::InitRasterizor()
{
	g_RootSig.Reset(1, 0);
	g_RootSig[0].InitAsConstants(0, sizeof(MatrixBuffer) / sizeof(float)); // Camera mat
	g_RootSig.Finalize(L"CubeRootSig", D3D12_ROOT_SIGNATURE_FLAG_ALLOW_INPUT_ASSEMBLER_INPUT_LAYOUT);

	D3D12_INPUT_ELEMENT_DESC layout[] =
	{
		{"POSITION", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 0, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0},
		{"NORMAL", 0, DXGI_FORMAT_R32G32B32_FLOAT, 0, 12, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0}
	};

	g_CubePSO.SetRootSignature(g_RootSig);
	g_CubePSO.SetInputLayout(_countof(layout), layout);
	g_CubePSO.SetRasterizerState({
		D3D12_FILL_MODE_SOLID, D3D12_CULL_MODE_NONE, true, -1, -1.f, 0, true, false, false, 0,
		D3D12_CONSERVATIVE_RASTERIZATION_MODE_OFF
	});
	D3D12_DEPTH_STENCIL_DESC depthStencilDesc;
	depthStencilDesc.DepthEnable = true;
	depthStencilDesc.DepthFunc = D3D12_COMPARISON_FUNC_GREATER_EQUAL;
	depthStencilDesc.StencilEnable = false;
	depthStencilDesc.DepthWriteMask = D3D12_DEPTH_WRITE_MASK_ALL;
	D3D12_DEPTH_STENCILOP_DESC stencilDesc{};
	depthStencilDesc.BackFace = stencilDesc;
	depthStencilDesc.FrontFace = stencilDesc;
	g_CubePSO.SetDepthStencilState(depthStencilDesc);
	D3D12_BLEND_DESC blendState;
	blendState.IndependentBlendEnable = false;
	blendState.RenderTarget[0].BlendEnable = false;
	blendState.RenderTarget[0].RenderTargetWriteMask = D3D10_COLOR_WRITE_ENABLE_ALL;
	g_CubePSO.SetBlendState(blendState);
	g_CubePSO.SetPrimitiveTopologyType(D3D12_PRIMITIVE_TOPOLOGY_TYPE_TRIANGLE);
	g_CubePSO.SetRenderTargetFormat(DXGI_FORMAT_R11G11B10_FLOAT, DXGI_FORMAT_D32_FLOAT);
	g_CubePSO.SetVertexShader(g_pVertexShader, sizeof(g_pVertexShader));
	g_CubePSO.SetPixelShader(g_pPixelShader, sizeof(g_pPixelShader));


	g_CubePSO.Finalize();

	vertexBuffer.Create(L"Cube vertices", _countof(cubeVertices), sizeof(cubeVertices[0]), &cubeVertices);
	indexBuffer.Create(L"Cube Indices", _countof(cubeIndices), sizeof(cubeIndices[0]), &cubeIndices);
}

#pragma endregion


CREATE_APPLICATION(PerformanceTestApplication)

void PerformanceTestApplication::Startup(void)
{
	GameCore::g_mouseLocked = false;

	Utility::Printf("Starting Volumarcher Performance tester\n");

	InitRasterizor();

	Utility::Printf("Creating Volumetric Context\n");
	CpuTimer startupTimer;
	startupTimer.Start();
	Volume volumes[VOLUME_AMOUNT] = {{float3(0, 0, 3.5f), 4.f, 5.f}};
	Volumarcher::CameraSettings cameraSettings{0.01f, 50.f, 70.f};
	m_volumetricContext = std::make_unique<Volumarcher::VolumetricContext>(volumes, cameraSettings);
	PostEffects::BloomEnable = false;
	PostEffects::EnableHDR = false;
	PostEffects::EnableAdaptation = false;
	startupTimer.Stop();

	Utility::Printf("VolumetricContext Startup Time: %fs\n", startupTimer.GetTime());

	StartTest();
}


void PerformanceTestApplication::Cleanup(void)
{
	// Free up resources in an orderly fashion
}

void PerformanceTestApplication::Update(const float _deltaTime)
{
	ScopedTimer _prof(L"Update State");

	if (GameInput::IsFirstPressed(GameInput::kKey_1))
	{
		g_currentTest = Test::BaseSampleCountSingle;
		StartTest();
	}
	else if (GameInput::IsFirstPressed(GameInput::kKey_2))
	{
		g_currentTest = Test::CloudCoverage;
		StartTest();
	}
	else if (GameInput::IsFirstPressed(GameInput::kKey_3))
	{
		g_currentTest = Test::Resolution;
		StartTest();
	}
	else
	{
	}

	framesInTest++;

	switch (g_currentTest)
	{
	case Test::BaseSampleCountSingle:
		{
			if (framesInTest > MAX_FRAMES_PER_TEST_PHASE)
			{
				delete pixTestTimer;
				cpuTestTimer.Stop();
				float hz = static_cast<float>(1.0 / (cpuTestTimer.GetTime() / static_cast<double>(
					MAX_FRAMES_PER_TEST_PHASE)));
				Utility::Printf("Test phase ran for: %fs | %fhz \n", cpuTestTimer.GetTime(), hz);

				testPhase++;
				framesInTest = 0;
				if (testPhase >= _countof(sampleCountTestSamples))
				{
					g_currentTest = Test::None;
					testPhase = 0;
					framesInTest = 0;
					return;
				}
				std::wstring testName = L"BaseSampleCountTest, Samples: " + std::to_wstring(
					static_cast<int>(sampleCountTestSamples[testPhase]));
				Utility::Printf("Starting test: %ls\n", testName.c_str());
				pixTestTimer = new ScopedTimer(testName);
				m_volumetricContext->SetSettings({
					static_cast<int>(sampleCountTestSamples[testPhase]), static_cast<int>(direct_samples),
					static_cast<int>(ambient_samples)
				});

				cpuTestTimer.Reset();
				cpuTestTimer.Start();
			}
			break;
		}
	case Test::CloudCoverage:
		{
			if (framesInTest > MAX_FRAMES_PER_TEST_PHASE)
			{
				delete pixTestTimer;
				cpuTestTimer.Stop();
				float hz = static_cast<float>(1.0 / (cpuTestTimer.GetTime() / static_cast<double>(
					MAX_FRAMES_PER_TEST_PHASE)));
				Utility::Printf("Test phase ran for: %fs | %fhz \n", cpuTestTimer.GetTime(), hz);

				testPhase++;
				framesInTest = 0;
				if (testPhase >= _countof(coverageCloudDistance))
				{
					g_currentTest = Test::None;
					testPhase = 0;
					framesInTest = 0;
					return;
				}
				std::wstring testName = L"CloudCoverage Test, Distance to cloud: " + std::to_wstring(
					static_cast<int>(coverageCloudDistance[testPhase] - 1.f)); // 1.f is radius of cloud
				Utility::Printf("Starting test: %ls\n", testName.c_str());
				pixTestTimer = new ScopedTimer(testName);
				m_camPos = {0, 0, -coverageCloudDistance[testPhase]};

				cpuTestTimer.Reset();
				cpuTestTimer.Start();
			}
			break;
		}
	case Test::Resolution:
		{
			if (framesInTest > MAX_FRAMES_PER_TEST_PHASE)
			{
				delete pixTestTimer;
				cpuTestTimer.Stop();
				float hz = static_cast<float>(1.0 / (cpuTestTimer.GetTime() / static_cast<double>(
					MAX_FRAMES_PER_TEST_PHASE)));
				Utility::Printf("Test phase ran for: %fs | %fhz \n", cpuTestTimer.GetTime(), hz);

				testPhase++;
				framesInTest = 0;
				if (testPhase >= _countof(resolutions))
				{
					g_currentTest = Test::None;
					testPhase = 0;
					framesInTest = 0;
					return;
				}
				std::wstring testName = L"Resolution test, res: " + std::to_wstring(
					static_cast<int>(resolutions[testPhase].x)) + L"x" + std::to_wstring(
					static_cast<int>(resolutions[testPhase].y));
				Utility::Printf("Starting test: %ls\n", testName.c_str());
				pixTestTimer = new ScopedTimer(testName);
				Display::Resize(resolutions[testPhase].x, resolutions[testPhase].y);

				cpuTestTimer.Reset();
				cpuTestTimer.Start();
			}
			break;
		}
	}


	//if (GameInput::IsFirstPressed(GameInput::DigitalInput::kKey_tab))
	//{
	//	GameCore::g_mouseLocked = !GameCore::g_mouseLocked;
	//	static int cursorPos[2]{0, 0};
	//}
	//if (GameCore::g_mouseLocked)
	//{
	//	//Rotation
	//	m_camYaw -= GameInput::GetAnalogInput(GameInput::kAnalogMouseX) * m_cameraRotSpeed;
	//	m_camPitch -= GameInput::GetAnalogInput(GameInput::kAnalogMouseY) * m_cameraRotSpeed;
	//	m_camPitch = glm::clamp(m_camPitch, -89.99f, 89.99f);
	//	m_camRot = glm::angleAxis(m_camYaw, glm::vec3(0, 1, 0)) * glm::angleAxis(m_camPitch, glm::vec3(1, 0, 0));
	//}


	////Movement
	//glm::vec3 input{0.f};
	//if (GameInput::IsPressed(GameInput::kKey_a)) input.x += 1;
	//if (GameInput::IsPressed(GameInput::kKey_d)) input.x -= 1;
	//if (GameInput::IsPressed(GameInput::kKey_w)) input.z += 1;
	//if (GameInput::IsPressed(GameInput::kKey_s)) input.z -= 1;
	//if (GameInput::IsPressed(GameInput::kKey_space)) input.y += 1;
	//if (GameInput::IsPressed(GameInput::kKey_c)) input.y -= 1;
	//if (glm::dot(input, input) > 0) input = normalize(input);
	//m_camPos += (m_camRot * input) * m_cameraSpeed * _deltaTime;
}


void PerformanceTestApplication::RenderRasterizerPass()
{
	GraphicsContext& graphicsContext = GraphicsContext::Begin(L"Graphics Pass");
	graphicsContext.TransitionResource(g_SceneColorBuffer, D3D12_RESOURCE_STATE_RENDER_TARGET, true);
	graphicsContext.TransitionResource(g_SceneDepthBuffer,
	                                   D3D12_RESOURCE_STATE_DEPTH_WRITE, true);
	graphicsContext.ClearColor(g_SceneColorBuffer);
	graphicsContext.ClearDepth(g_SceneDepthBuffer);
	graphicsContext.SetRenderTarget(g_SceneColorBuffer.GetRTV(), g_SceneDepthBuffer.GetDSV());
	graphicsContext.SetViewportAndScissor(0, 0, g_SceneColorBuffer.GetWidth(), g_SceneColorBuffer.GetHeight());
	graphicsContext.SetRootSignature(g_RootSig);
	graphicsContext.SetPipelineState(g_CubePSO);

	graphicsContext.SetPrimitiveTopology(D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST);

	D3D12_VERTEX_BUFFER_VIEW vbv;
	vbv.BufferLocation = vertexBuffer.GetGpuVirtualAddress();
	vbv.SizeInBytes = vertexBuffer.GetBufferSize();
	vbv.StrideInBytes = sizeof(Vertex);

	D3D12_INDEX_BUFFER_VIEW ibv;
	ibv.BufferLocation = indexBuffer.GetGpuVirtualAddress();
	ibv.SizeInBytes = indexBuffer.GetBufferSize();
	ibv.Format = DXGI_FORMAT_R16_UINT;

	graphicsContext.SetVertexBuffer(0, vbv);
	graphicsContext.SetIndexBuffer(ibv);

	glm::vec3 camDir = m_camRot * glm::vec3(0, 0, 1);
	glm::mat4 view = glm::lookAtRH(m_camPos, m_camPos + camDir, glm::vec3(0, 1, 0));
	static const glm::mat4 projection = glm::perspectiveRH_ZO(glm::radians(70.f), (16.f / 9.f), 50.f, 0.01f);

	MatrixBuffer constants{projection * view};
	graphicsContext.SetConstantArray(0, sizeof(MatrixBuffer) / sizeof(uint32_t), &constants);

	graphicsContext.DrawIndexed(_countof(cubeIndices));


	graphicsContext.Finish();
}

void PerformanceTestApplication::StartTest()
{
	m_volumetricContext->SetSettings({
		static_cast<int>(base_samples), static_cast<int>(direct_samples), static_cast<int>(ambient_samples)
	});
	Volume volumes[VOLUME_AMOUNT] = {{float3(0, 0, 3.5f), 4.f, 5.f}};
	m_volumetricContext->SetVolumes(volumes);
	m_camPos = {0.f, 0.f, 0.f};
	Display::Resize(1920, 1080);


	switch (g_currentTest)
	{
	case Test::BaseSampleCountSingle:
		{
			testPhase = 0;
			framesInTest = 0;
			std::wstring testName = L"BaseSampleCountTest, Samples: " + std::to_wstring(
				static_cast<int>(sampleCountTestSamples[testPhase]));
			Utility::Printf("Starting test: %ls\n", testName);
			pixTestTimer = new ScopedTimer(testName);
			cpuTestTimer.Reset();
			m_volumetricContext->SetSettings({
				static_cast<int>(sampleCountTestSamples[testPhase]), static_cast<int>(direct_samples),
				static_cast<int>(ambient_samples)
			});
			cpuTestTimer.Start();
			break;
		}
	case Test::CloudCoverage:
		{
			testPhase = 0;
			framesInTest = 0;
			Volume volumes[VOLUME_AMOUNT] = {{float3(0, 0, 0), 1.f, 10.f}};
			m_volumetricContext->SetVolumes(volumes);
			std::wstring testName = L"CloudCoverage, Cloud distance: " + std::to_wstring(
				static_cast<int>(coverageCloudDistance[testPhase]));
			Utility::Printf("Starting test: %ls\n", testName);
			pixTestTimer = new ScopedTimer(testName);
			cpuTestTimer.Reset();
			m_volumetricContext->SetSettings({
				static_cast<int>(base_samples), static_cast<int>(direct_samples), static_cast<int>(ambient_samples)
			});
			cpuTestTimer.Start();
			break;
		}
	case Test::Resolution:
		{
			abort(); // TODO: implement this
			testPhase = 0;
			framesInTest = 0;
			std::wstring testName = L"Resolution test, res: " + std::to_wstring(
				static_cast<int>(resolutions[testPhase].x)) + L"x" + std::to_wstring(
				static_cast<int>(resolutions[testPhase].y));
			Utility::Printf("Starting test: %ls\n", testName);
			pixTestTimer = new ScopedTimer(testName);
			cpuTestTimer.Reset();
			Display::Resize(resolutions[testPhase].x, resolutions[testPhase].y);

			cpuTestTimer.Start();

			break;
		}
	}
}


void PerformanceTestApplication::RenderScene(void)
{
	switch (g_currentTest)
	{
	case Test::BaseSampleCountSingle:
	case Test::CloudCoverage:
	case Test::Resolution:
		m_volumetricContext->Render(g_SceneColorBuffer,
		                            D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE |
		                            D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE, g_SceneDepthBuffer,
		                            m_camPos,
		                            m_camRot);
		break;
	}

	//RenderRasterizerPass();
	//m_volumetricContext->Render(g_SceneColorBuffer, D3D12_RESOURCE_STATE_RENDER_TARGET, g_SceneDepthBuffer, m_camPos,
	//                            m_camRot);
}
